- src/modules/uv-shared-module/baseProvider.ts
Right now, the logic for displaying a PDF download link only works if exactly one service is configured. However, it seems realistic that a manifest might define multiple services for a single sequence (i.e. "PDF Download," "MS Word Download," etc.). This PR makes the code a bit more flexible so it can handle both single- and multi-valued service entries.
Note that I'm not sure if this is up to spec, but it seems like a reasonable use case.
Assuming that multiple services are legal in the spec (and I think they should be), another consideration is the possibility of multiple PDF services for the same sequence (e.g. differently formatted renderings of the same content); it seems that it might be reasonable to account for this, and also to make use of the label property found in the service …
> Handle sequences with multiple services correctly.

- src/extensions/uv-seadragon-extension/provider.ts
I couldn't get the latest master to compile under Ubuntu. I'm guessing this is a case sensitivity problem introduced through Windows-based development. In any case, the change here seems to fix the build.
> Fixed case sensitivity issue.

- src/extensions/uv-seadragon-extension/extension.ts
If you tried to go past the beginning or end of the page list (either by holding down pageUp/pageDown or by clicking on the disabled prev/next controls) the entire interface would stop responding. This was caused by a "this.loading" flag being set to true PRIOR to the out-of-range check. Adjusting the order of the lines fixed the problem.
> Fixed bug: scrolling past edge of list would break viewPage().

- src/modules/uv-treeviewleftpanel-module/treeViewLeftPanel.ts
My items do not use an alternate sequence, so there is no use for the index tab. This PR hides the index tab when the tree it represents is empty. Perhaps there is a more efficient way to achieve the same effect, but this at least seems to work correctly for me.
> Hide index tab when empty.

- src/bootstrapper.ts
- src/modules/uv-shared-module/baseProvider.ts
As discussed in #54, this allows the choice between "force CORS," "force JSONP" and "autodetect based on capabilities."
Note that there seems to be a problem with the way utils.getBool() was being used to initialize the jsonp value in the bootstrapper -- even though the property is typed as boolean, it was actually getting assigned a string of "true" or "false". This inconsistency caused problems down the line since all values would evaluate to boolean true. I tried to fix getBool to convert strings like "true" and "false" to equivalent boolean values, but this caused the entire application to break -- I think there may be some code making undesirable assumptions somewhere. Rather than delve deeper into that problem, I opted to simply work around getBool entirely for the purposes of this …
> More granular control over CORS/JSONP behavior.

- src/extensions/uv-seadragon-extension/downloadDialogue.ts
- src/extensions/uv-seadragon-extension/l10n/en-GB.json
- src/extensions/uv-seadragon-extension/l10n/xx-XX.json
It's rather confusing that the page mode determines which download options are available (though I understand the reasoning behind it). This PR adds messaging to alert users' attention to this fact.
This is intended as a proof of concept and is not really fit to be merged as-is; I was unable to provide a Welsh translation, and I'm sure better wording/styling/positioning could be determined for the actual message. Ideally it would be nice if we could really focus the user's attention on which button they need to press to fix the problem (or even offer a functioning option within the download box) since this is not at all obvious in my opinion.
Anyway, I hope this is a foundation that can be built upon. I'm happy to do more work on this if you have suggestions on a forward course.
> Display download warning when in two-up page mode.

- src/extensions/uv-seadragon-extension/DownloadOption.ts
- src/extensions/uv-seadragon-extension/downloadDialogue.ts
- src/extensions/uv-seadragon-extension/l10n/cy-GB.json
- src/extensions/uv-seadragon-extension/l10n/en-GB.json
- src/extensions/uv-seadragon-extension/l10n/xx-XX.json
Presently, individual images can only be downloaded as JPEGs. We would like to also allow direct download of the TIFFs specified by our manifest for users who desire the full original image. This PR adds that functionality. I imagine that not everyone may want this. If you feel that this should be made configurable in some fashion, please let me know and I can make adjustments.
> Allow download of original images from manifest.

- src/extensions/uv-seadragon-extension/downloadDialogue.ts
This is another feature that should perhaps be configurable; let me know if you'd like me to do more work on that.
This also brings up a related point: right now, the handling of PDF/Doc/Docx is very static and assumes just one file of each type. However, I could imagine situations where you might have multiple files of a single format with different labels (for example, one PDF containing all of the page images of a hand-written letter, and another PDF containing a textual transcription of the text from the letter). I suspect that rearchitecting this to allow that sort of situation might also lead to cleaner, less redundant code, but it also looks like a substantial refactoring/redesign project. I don't actually need to support this case (yet) but I might be able to find time to work on …
> Display labels from manifest on renderings in download dialogue.

- src/extensions/uv-seadragon-extension/DownloadOption.ts
- src/extensions/uv-seadragon-extension/downloadDialogue.ts
- src/extensions/uv-seadragon-extension/l10n/cy-GB.json
- src/extensions/uv-seadragon-extension/l10n/en-GB.json
- src/extensions/uv-seadragon-extension/l10n/xx-XX.json
This PR addresses recent discussions about dealing with original images and OCR. Here is a summary of changes:
1.) Removed separate handling of doc/docx/pdf in favor of generic handling of sequence renderings.
2.) Removed separate handling of original images in favor of generic handling of canvas/image renderings.
3.) Changed existing "high res jpg" functionality to a more generic "link to @id of image element" feature.
Notes:
- Given the way this has evolved, I'm not sure if the DownloadOption mechanism still makes sense; however, in the interest of being comparatively non-disruptive, I left it alone for the moment.
- I imagine that we might want configuration options for filtering out unwanted MIME types from the rendering lists.
- I created a simplistic routine for mapping mime-types …
> Made download dialog box more dynamic, with support for more renderings.

- src/extensions/uv-seadragon-extension/downloadDialogue.ts
This addresses the one remaining "to do" from my previous pull request.
Now when the dimensions of the full "high res" version are smaller than the constraints used to generate the "low res" version, we hide the "low res" download link.
Arguments could be made about how the one remaining link should be labeled in this situation; it might make sense to add a new text string that says neither "high res" or "low res" since these terms are just about meaningless when not used relative to one another. However, for simplicity's sake, I just kept "high res" in the case where it's really "only res".
Also note that I'm only comparing width here, since it appears that width is the only dimension which can be constrained through the confinedImageSize setting (if I'm reading the code correctly). If …
> Hide "low-res" option when inapplicable.

- src/lib/jquery.plugins.js
The more/less logic was overzealous and would ALWAYS display a truncation control regardless of the target length of the string. This makes the control conditional, so it's only displayed when actually needed.
> Don't display "more" if the string is shorter than the character limit.

- Gruntfile.js
After cleaning out my directory tree and starting anew, this is the fix that seems to allow everything to build correctly without renaming any files.
> Fixed case problems.

- src/extensions/uv-seadragon-extension/Provider.ts
- src/modules/uv-shared-module/BaseProvider.ts
The logic for displaying two pages side-by-side only worked correctly in items with even numbers of canvases due to explicit assumptions about how the last page should be handled. In a book with an odd number of canvases, clicking on the last page vs. clicking on the second-to-last page would result in inconsistent behaviors, even though in this instance, the two pages should be shown side-by-side. This fix should correct the issue (I tested with both odd and even canvas counts, and both cases work correctly now).
> Fix display of last two pages in books with odd number of canvases.

- src/extensions/uv-pdf-extension/Extension.ts
- src/extensions/uv-pdf-extension/config/en-GB.json
- src/modules/uv-treeviewleftpanel-module/GalleryView.ts
- src/modules/uv-treeviewleftpanel-module/ThumbsView.ts
I believe this PR fixes the remaining major issues mentioned last week and gets the PDF extension to a bare minimum of functionality for multiple-PDF manifests:
- I fixed a fatal error caused by a call to this.extension.getMode(), when getMode() is not defined by the PDF extension. I opted to detect the presence of the method and work around it when missing rather than implementing the method in the extension, since it looked like an implementation would require loading Seadragon-specific classes into the PDF extension. Perhaps this is a sign that something isn't living in the best possible location.
- I added some missing configuration to solve the "NaN thumbnail problem" in the left sidebar. However, for now, all thumbnails show "Image Unavailable."
- I fixed the resizing behavior …
> More PDF extension fixes.

- src/extensions/uv-mediaelement-extension/Extension.ts
- src/extensions/uv-mediaelement-extension/config/en-GB.json
This PR adds support for multi-canvas audio/video (i.e. "cassette side A", "cassette side B"), with changes modeled on my recent work with the PDF extension. As with that work, this is bare minimum, and there are probably some cosmetic improvements yet to be made (such as better thumbnail options).
One question specific to this extension: there was an existing check for multiple sequences (rather than multiple canvases). I opted to OR the two options together in case the multi-sequence use case is actually necessary, but I have a suspicion this may be something legacy that is no longer meaningful. If there's a real example of a multi-sequence media manifest out there, I'd be happy to test it against this code and see if anything breaks.
Thanks!
> Allow multi-canvas media manifest.

- src/modules/uv-mediaelementcenterpanel-module/MediaElementCenterPanel.ts
My audio manifests include renderings in several audio formats (flac/ogg/mp3). By picking the first rendering, it is possible that the viewer will attempt to play an unsupported format. This modification searches the list for audio/mp3 and only fails over to the first entry if no MP3 is found. It might make sense to extend this list to cover more audio formats or even to allow a configuration setting to set an order of preference for formats. However, this simple fix is good enough for my local needs.
> When multiple audio sources are available, favor MP3

- src/app.html
I am thoroughly confused about what is going on here. After you merged my pull request and I pulled down the latest master (totally resetting everything, deleting all files, reinstalling dependencies, etc.) I found myself encountering case sensitivity problems yet again. Putting it back the way it was got it working again. I'm not sure what could have changed!
The previous time that I was encountering problems (when I changed "app" to "App") the failure had to do with the browser attempting to load src/App.js. But this time (when I'm changing "App" back to "app") the problem had to do with the browser attempting to load App.js from inside the built application, where the filename is actually app.js.
I've tried to be consistent in my procedures for resetting and building, so I'm not sure …
> Undo case switch.

- src/extensions/uv-seadragon-extension/Provider.ts
I just noticed that the "current view" and "whole image low res" download options were not working in the latest master. These were working a couple of weeks ago, prior to my vacation. It appears that the issue is that getBaseUri was including the image ID when it shouldn't have, which was resulting in invalid IIIF URIs with doubled-up ID values in them. I believe that this PR should fix the problem, though I'm not sure when/where/why the bug was originally introduced.
> Fixed problem with ID being included in base URI.

- src/extensions/uv-pdf-extension/config/en-GB.json
- src/modules/uv-pdfcenterpanel-module/PDFCenterPanel.ts
Our collection contains several PDF files that the pdf.js code included with UV is unable to render correctly. However, the PDFObject method, while slower, appears to have better broad-spectrum compatibility. Thus, I have added a configuration setting to optionally disable pdf.js.
As time permits, I still plan to do some more work to upgrade pdf.js and see if I can track down the root cause of the problems. Given that pdf.js is built into Firefox natively, there has to be an explanation as to why that version works fine but the one bundled in UV breaks.
> Add config setting to disable pdf.js.

- .travis.yml
Tests are working!
This may be a bit fragile for two reasons:
1.) Travis doesn't support Chrome by default, and the new container infrastructure doesn't make it easy to install, so we have to download the compiled binary from a fixed location.
2.) This binary distribution has problems with the sandbox, so we have to use the --no-sandbox switch (bad security practice, but in this context I don't think we care). I tried to work around this in other ways but didn't find an easy fix.
Bottom line: it works, but it might eventually stop working. I figure we can cross that bridge when we come to it!
> Working tests in Travis.

- src/modules/uv-mediaelementcenterpanel-module/MediaElementCenterPanel.ts
My audio manifests don't currently include thumbnails. This was causing a 404 error for an image called "undefined." I adjusted the code to only include the poster attribute if a poster image URI is found.
This appears to work fine with the "Florence Nightingale" Wellcome example, so I think both with-thumb and without-thumb cases are now properly handled.
> Don't try to set a poster attribute if no poster exists.

- src/modules/uv-seadragoncenterpanel-module/css/styles.less
If you click inside the OSD canvas but beside the image a blue or dotted line appears all around the OSD canvas, this patch removes that line.
> Removed the OSD element outline 

- src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts
Hi!
This is a fix for a crash that occurred for us with certain images. If you didn't touch the image after load and directly tried to navigate to the next one, currentBounds wasn't set and threw an exception.
> Fix crash on navigation if currentBounds wasn't set.

- src/modules/uv-treeviewleftpanel-module/TreeViewLeftPanel.ts
- Prevents errors in non-Seadragon extensions.
> Avoid fatal error when getSortedTree() is undefined.

- src/extensions/uv-seadragon-extension/Extension.ts
- src/extensions/uv-seadragon-extension/config/en-GB.json
- src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts
- src/modules/uv-shared-module/BaseExtension.ts
Hi again!
I found the merge conflict and fixed it. This patch adds an option to allow using the arrow keys for scrolling in OSD instead of navigating between pages. It also fixes so that page up, page down, home and end doesn't scroll the browser window if UV has focus.
I've taken out the code for zooming, lets wait for OSD 2.1 on that one.
> Option to use arrow keys for scrolling in OSD

- src/extensions/uv-seadragon-extension/ISettings.d.ts
- src/extensions/uv-seadragon-extension/SettingsDialogue.ts
- src/extensions/uv-seadragon-extension/config/en-GB.json
- src/extensions/uv-seadragon-extension/l10n/en-GB.json
- src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts
Hi!
This patch adds a new option to the settings dialog where you can enable or disable the navigator.
It also removes the option "showNavigator" in "seadragonCenterPanel" and adds a new option "navigatorEnabled" at the top instead.
> Add option in settings dialog to enable and disable the navigator

- src/extensions/uv-seadragon-extension/config/en-GB.json
- src/modules/uv-shared-module/BaseExpandPanel.ts
This is an option to disable the expand full button in the left panel. We currently do not have thumbs enabled, which makes the full view kind of useless for us, and a bit confusing.
> Added option to disable the expand full button.

- src/extensions/uv-seadragon-extension/ISettings.d.ts
- src/extensions/uv-seadragon-extension/SettingsDialogue.ts
- src/extensions/uv-seadragon-extension/config/en-GB.json
- src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts
- src/modules/uv-shared-module/BaseProvider.ts
- src/modules/uv-shared-module/HeaderPanel.ts
Hi again!
I used your new code for saving to localStorage to implement saving of the options in the settings dialog. It saves the setting for navigator, paging and viewport, but not the language. I set it to save for 10 years, don't know if that's a good idea or not.
> Added option to save user settings to localStorage.

- src/extensions/uv-mediaelement-extension/l10n/en-GB.json
- src/extensions/uv-pdf-extension/l10n/en-GB.json
- src/extensions/uv-seadragon-extension/l10n/en-GB.json
- src/modules/uv-shared-module/BaseProvider.ts
- src/modules/uv-shared-module/UriLabeller.ts
This is intended as a proof of concept -- I don't think it's useful to merge as-is.
The idea is that we want to be able to display descriptions associated with the license URLs. I've just populated this with a single URL to allow the "Bride of the Tomb" example to work correctly. Ideally I think we would want the labels to account for i18n and be able to easily pull from local configuration... but I wasn't sure how to address that all the way down at the BaseProvider level where we need it.
Thoughts?
> Basic mechanism for displaying text links for licenses.

- src/extensions/uv-seadragon-extension/config/en-GB.json
- src/extensions/uv-seadragon-extension/l10n/en-GB.json
- src/modules/uv-moreinforightpanel-module/MoreInfoRightPanel.ts
- src/modules/uv-moreinforightpanel-module/css/styles.less
Hi!
This is the pull request for issue #188. This picks up any metadata values defined inside of canvases in the manifest. It works pretty much the same as when defining global metadata values, but it places the values in a new section at the bottom of the right panel. 
The text of the headers can both be configured and does not show if they are empty. A section does not show if there is no metadata for it in the manifest.
The configuration "aggregateValues" combines values from manifest level metadata and canvas level metadata. It takes a comma separated list that should match the value of the label in the metadata. If it finds a match in the canvas metadata, the matching values are aggregated.
For example we declare most of the source reference information only once in the manifest and …
> Image specific information in the right panel

- src/modules/uv-moreinforightpanel-module/MoreInfoRightPanel.ts
This PR hides the manifest header if there is no canvas metadata, as talked about in #243.
> Hide manifest header if no canvas metadata is present

- src/extensions/uv-mediaelement-extension/config/en-GB.json
- src/extensions/uv-pdf-extension/config/en-GB.json
- src/extensions/uv-seadragon-extension/config/en-GB.json
- src/extensions/uv-virtex-extension/config/en-GB.json
- src/modules/uv-moreinforightpanel-module/MoreInfoRightPanel.ts
- src/modules/uv-shared-module/BaseProvider.ts
- src/modules/uv-shared-module/IProvider.ts
This PR introduces a new option `canvasExclude` and renames `exclude` to `manifestExclude`. The only value that canvas can read for now is `metadata`, but I have tried to make it easy to add other values later on. I also made it so that the canvas title isn't shown if there is only values in canvas and not in the manifest.
Maybe all the code for manipulating the metadata should really be in some provider instead? It should be pretty easy to move parts of it now anyway.
> Exclude option for canvas metadata

- src/extensions/uv-seadragon-extension/DownloadDialogue.ts
- Always use guaranteed-unique IDs for download radio buttons!
- Resolves #266.
> Fix bug: duplicate labels caused duplicate IDs, breaking downloads.

- src/modules/uv-shared-module/BaseExtension.ts
Firefox uses Ctrl+PageDown to switch between tabs. We check if Ctrl, Alt or Shift are pressed together with UV keys and don't trigger an UV-event if they are pressed.
> Check if Ctrl, Alt and Shift are pressed with UV keys

- src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts
We found this while testing for persistent XSS vulnerabilities. We fixed the problem using the same solution that is used in MoreInfoRightPanel.
> Fixing XSS vulnerability in center panel

- src/Bootstrapper.ts
Without the code in this PR, there is a bug in the UV where clicking on a subcollection that contains only subcollections (not manifests) leads to a fatal error. You can reproduce this by loading the Villanova University Digital Library collection (http://digital.library.villanova.edu/Collection/vudl:3/IIIF) and clicking on the "Dime Novel and Popular Literature" collection in the Index.
This PR adds logic so that, if no manifests are found immediately within a subcollection, the bootstrapper will recurse deeper until it finds something.
This behavior is definitely better than a fatal error, but it does have some disadvantages:
- If we have more than two levels of nested collections without manifests, some parts of the tree will be inaccessible because the UV will follow the tree downward …
> Deep collection fix

- src/modules/uv-resourcesleftpanel-module/ResourcesLeftPanel.ts
- Hide 'resources' div when unused.
- Explicitly set height of 'views' container.
> Fixed problems with sizing of ResourcesLeftPanel.

- src/extensions/uv-seadragon-extension/l10n/en-GB.json
> Updated en-GB.json to make manifest header generic

- src/modules/uv-searchfooterpanel-module/FooterPanel.ts
If there is a XSS injection in a label then it will be executed because of the unsafe nature of the html function.
> Fixing XSS vulnerability in FooterPanel

- src/app.ts
Since jQuery gets loaded before requirejs in app.html it doesn't detect
requirejs and doesn't get  defined properly. Issue #388
> making requirejs aware that jQuery is already loaded

- src/extensions/uv-seadragon-extension/DownloadDialogue.ts
What I changed:
* src/extensions/uv-seadragon-extension/Extension.ts: 
the attribute is now set to the value of url parameter "rotation" instead of the default value 0. Before, this value was only updated when a trigger from openseadragon was fired.
* src/extensions/uv-seadragon-extension/DownloadDialogue.ts: 
* for rotated images of 180 and 270 degrees, the order of width and height are reversed in the labels, for these are the dimensions of the resulting images. For some reason the width and height are also stored in the buttons, but I don't know why. What are they for?
* the rotation parameter in the uri for highRes and lowRes are set to the current rotation.
> reverse w x h for download labels; change rotation param in computed uri

- src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts
The onclick event for the rotateButton in Firefox is never fired.
It does in Chrome. Seems like this event is prevented from
propagating?
Consequences:
* this.currentRotation is never changed to anything but the initial value
* this.currentRotation is only set to something different than 0 when loaded from the url parameter
* download buttons do not see the rotation (they use this.currentRotation)
This should work in both browsers. Don't know about Safari or IE.
> on click rotateButton event never fired in Firefox

- src/extensions/uv-pdf-extension/Extension.ts
THUMB_SELECTED event handler is updated to correctly handle the thumb
object that is passed (as opposed to the integer index which was
previously assumed).
> Fix thumb selection event

- src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts
Sometimes the images that gets the bounds of a previous image
with fitBounds is not visible.
> Solving problem with Preserve Zoom and images with different sizes

- src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts
this.currentBounds is sometimes a string, and sometimes an object of class Bounds.
The first thing happens when the width and height of the viewport are resized.
> this.currentBounds not always a string

- src/extensions/uv-mediaelement-extension/Extension.ts
We noticed that multi-part audio items weren't working correctly. This fixes the problem.
> Fixed type mismatch

- src/uv.html
When root was set to ../uv, uv.html then would fail in any non-default directory. Using . makes this more portable.
> Fixed root path to be more generic

- src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts
Fixes https://github.com/sul-dlss/universalviewer/issues/13
> keeps OSD prev/next controls enabled on focus or mousehover

- src/modules/uv-shared-module/Auth1.ts
Without this, the `\n` is not respected in the rendered dialogue.
> wrap auth header in a <p>

- src/modules/uv-dialogues-module/ShareDialogue.ts
From https://www.w3.org/TR/html401/interact/forms.html#adef-readonly
Running through: https://validator.w3.org
```html
<!DOCTYPE html>
<html>
<head><title>not valid</title></head>
<body>
<input readonly="true">
</body>
</html>
```
```html
<!DOCTYPE html>
<html>
<head><title>valid</title></head>
<body>
<input readonly>
</body>
</html>
```
> readonly attribute does not use a value

- src/modules/uv-searchfooterpanel-module/FooterPanel.ts
- src/modules/uv-shared-module/FooterPanel.ts
- src/modules/uv-shared-module/css/footer-panel.less
- src/modules/uv-shared-module/css/icons.less
- src/modules/uv-shared-module/css/mixins-extended.less
- src/modules/uv-shared-module/css/styles.less
- src/modules/uv-shared-module/css/variables.less
Can be turned on by setting font-size: 0.75rem to buttons
This PR also adds a consolidated way to define icons. Additional work could be done to consolidate the rest of the icon definitions. These buttons now are not offset or have the images padded, but instead are appropriately spaced.
> Add back button content in footer

- src/modules/uv-pagingheaderpanel-module/PagingHeaderPanel.ts
- src/modules/uv-pagingheaderpanel-module/css/icons.less
- src/modules/uv-pagingheaderpanel-module/css/styles.less
- src/modules/uv-shared-module/HeaderPanel.ts
- src/modules/uv-shared-module/css/header-panel.less
- src/modules/uv-shared-module/css/icons.less
A follow on to #503 . This PR moves the header panel icons/buttons to the same approach as the footer panel. The overall aim here is to simplify the styling needs for these buttons.
> move header icon buttons to consolidated approach, fixing spacing

- src/extensions/uv-seadragon-extension/config/en-GB.json
- src/modules/uv-pagingheaderpanel-module/PagingHeaderPanel.ts
- src/modules/uv-searchfooterpanel-module/FooterPanel.ts
- src/modules/uv-shared-module/AutoComplete.ts
This allows for adopters to use a multi word search for autocomplete. ~~If desired I can push this into a configuration or setting instead.~~
35b97366f1c904da310454b74a855c626af68711 moves this into a configuration option that can be used by a module to implement individually (`FooterPanel` or `PagingHeaderPanel`). The default option is the previous behavior.
> allow for multi word autocomplete searches

- src/modules/uv-mediaelementcenterpanel-module/MediaElementCenterPanel.ts
Without this change the initial height gets stuck and does not adjust to resizing the browser
> Fixed default audio width and height

- __tests__/configuration_options.js
- src/UVComponent.ts
- src/extensions/uv-seadragon-extension/config/en-GB.json
- src/modules/uv-shared-module/ThumbsView.ts
This supports both browser and server side thumbnail caching
configurations.
Fixes #537 
Fixes #431 
This PR also fixes an issue (in cffcd4c) where when using `UVComponent#set`, the data you are setting it to was actually not merged back into the config.
~~I'm still looking into a way to test this. Likely will need to make changes to how `/examples` works to do so.~~
Updated with integration tests. Testing `UVComponent` by itself will likely require some more work to look into handle that.
> Adds a configurable way to set thumbnail caching

- src/modules/uv-pdfcenterpanel-module/PDFCenterPanel.ts
Fix for the issue where changing PDF canvases did not reset the page number to 1
> Fix for PDF canvas index issue

- src/extensions/uv-seadragon-extension/Extension.ts
We use Solr as our backend for full-text searching, and users are instructed on how to use + to require words. But the plus (and other special characters) were not being encoded in the search request, so they were not functioning properly.
This change simply encodes the search terms in the URI.
> Encode search terms in URI request

- src/modules/uv-mediaelementcenterpanel-module/css/overrides.less
Small css change so the attribution/requiredStatement displays properly for AV manifests
> MediaElement - display attribution/requiredStatement

- src/modules/uv-mediaelementcenterpanel-module/css/overrides.less
So that they aren't hidden by the Attribution statement
> Setting z-index for overlays (download, share, etc.)

- src/modules/uv-searchfooterpanel-module/FooterPanel.ts
When you hit the search button in the footer panel, and the query is empty,
you'll get an javascript error in the console (not noticeable by the user):
```
Uncaught TypeError: Cannot read property 'genericDialogue' of undefined
at FooterPanel.search (FooterPanel.js:282)
at HTMLAnchorElement.<anonymous> (FooterPanel.js:103)
at HTMLAnchorElement.dispatch (offline.js:2)
at HTMLAnchorElement.y.handle (offline.js:2)
```
Reason: typo
> fix typo; error when hitting search button with no value

- src/modules/uv-contentleftpanel-module/ContentLeftPanel.ts
- src/modules/uv-dialogues-module/ShareDialogue.ts
- src/modules/uv-filelinkcenterpanel-module/FileLinkCenterPanel.ts
- src/modules/uv-searchfooterpanel-module/FooterPanel.ts
- src/modules/uv-shared-module/CenterPanel.ts
- src/modules/uv-shared-module/HeaderPanel.ts
These changes get some way towards making UV compatible with XHTML 5. There remain some incompatibilities brought in as dependencies in the build process, which will need to be fixed upstream before full compatibility is achieved.
There are three types of problem that need to be fixed: 
1. Attributes must have explicit, quoted, values.
2. Named character entities other than `&quot;`, `&apos;`, `&lt;`, `&gt;`, and `&amp;` are not allowed.
3. All markup must be well-formed
> Improve XHTML compatibility

- package.json
- src/modules/uv-avcenterpanel-module/AVCenterPanel.ts
Modifies the arguments passed to the AVComponent constructor in order to support the changes introduced into `@iiif/iiif-av-component` with https://github.com/IIIF-Commons/iiif-av-component/pull/35.
I can issue this as a full pull request following a new patch or minor release for https://www.npmjs.com/package/@iiif/iiif-av-component
> Provides the posterImageExpanded argument to the AVCenterPanel constructor

- src/modules/uv-dialogues-module/ShareDialogue.ts
- src/modules/uv-shared-module/BaseExtension.ts
- src/modules/uv-shared-module/IExtension.ts
Currently, at the Princeton University Library, we have cases where we use the Universal Viewer to access `sc:Collections` with multiple volumes as manifests.  Please see the following example:
http://universalviewer.io/examples/#?c=&m=&s=&cv=&manifest=https%3A%2F%2Ffiggy.princeton.edu%2Fconcern%2Fscanned_resources%2Fabcbea26-6600-4445-be9f-bf0ac0ba965a%2Fmanifest&xywh=-1549%2C-787%2C5665%2C5114
When users attempt to use the drag-and-drop icon within the share dialogue to integrate with an application such as [Mirador](http://projectmirador.org/demo/), these can break.  In order to avoid these types of compatibility issues, we have modified the URL generation for this in order to just provide the manifest for the canvas selected for viewing.
> Share manifest URIs for cases where a IIIF Collection is being viewed

- src/extensions/uv-pdf-extension/l10n/cy-GB.json
- src/extensions/uv-pdf-extension/l10n/fr-FR.json
- src/extensions/uv-pdf-extension/l10n/sv-SE.json
- src/extensions/uv-pdf-extension/theme/treeviewleftpanel.less
Fixing issue where the Welsh and other translations were not displaying in the header when on the PDF viewer.
Currently the buttons show as 'undefined' when changing to a language other than English
http://universalviewer.io/examples/?manifest=http://wellcomelibrary.org/iiif/b17502792/manifest#?c=&m=&s=&cv=&manifest=https%3A%2F%2Fedsilv.github.io%2Ftest-manifests%2Fpres3-pdf.json
> Adding translation into header of PDF view.

- src/modules/uv-pdfcenterpanel-module/PDFCenterPanel.ts
Small change to make PDF.js use credentialed requests if the canvas has auth services, allowing PDFs to be used with the proto-auth 2.x probe service
> Use credentialed requests for PDFs when auth services present

- src/modules/uv-pdfcenterpanel-module/PDFCenterPanel.ts
We have an issue where large PDFs aren't rendering to the correct size in the PDF viewer:
e.g https://www.peoplescollection.wales/items/1561611
The example above shows a large PDF being zoomed too far in on page load. 
I believe this is a similar issue to #622.
The work around I have is to set the height of the canvas with CSS. I don't have access to a Windows machine, therefore, I have been unable to check how this works on IE/Edge. But testing locally (OSX), it works on Chrome, Firefox and Safari.
The PDF in my example and the one in #622 work fine.
Diolch/Thanks
> adding a way to allow large pdfs to zoom to the correct size

- src/extensions/uv-mediaelement-extension/Extension.ts
When a canvas with a `Sound` annotation body type is given, this code will throw `Unable to determine media type` instead of returning false and allowing it to continue with an audio element
> Return false from isVideo if not a video

- esbuild.mjs
- npm-examples/esbuild/.gitignore
- npm-examples/esbuild/esbuild.mjs
- npm-examples/esbuild/package.json
- npm-examples/esbuild/src/index.ts
- npm-examples/esbuild/src/main.css
- npm-examples/react-scripts/.gitignore
- npm-examples/react-scripts/package.json
- npm-examples/react-scripts/public/index.html
- npm-examples/react-scripts/src/style.css
- package-lock.json
- package.json
- src/UniversalViewer.ts
- src/Utils.ts
- src/index.ts
- src/modules/uv-modelviewercenterpanel-module/ModelViewerCenterPanel.ts
- src/modules/uv-pdfcenterpanel-module/css/styles.less
- src/modules/uv-slideatlascenterpanel-module/css/styles.less
- src/shim-jquery.ts
- tsconfig.json
This PR adds in a few package publishing options, and a way to test them (before publishing to NPM)
The package.json for publishing looks like this:
```json
{
"main": "dist/cjs/index.js",
"module": "dist/esm/index.js",
"typings": "dist/cjs/index.d.ts",
"web": "dist/umd/UV.js"
}
```
* `main` - this is what some bundlers will go for, and typically expect node-like imports (require) and don't have lazy loading included. The CJS folder contains all of the individual files (from typescript compiler)
* `module` - this is used by more modern bundlers (recent webpack, esbuild etc.) and has module import/export. This is code-split similar to the webpack bundle, but is aimed at bundlers themselves (or modern browsers)
* `typings` - this will offer type-assistance for anyone importing in Typescript …
> NPM package publishing

- src/UniversalViewer.ts
The registry has a mapping for `image`
But this fails for image formats, since they typically appear as `image/jpg` or `image/png`. There is a separate `image/jpeg` definition, which could also be removed. This should catch images of any format.
> Fixed loading images into UV

- src/content-handlers/iiif/modules/uv-searchfooterpanel-module/FooterPanel.ts
Within searchfooterpanel extension, FooterPanel.ts incorrectly used `this.extensions` to access the default label when the label is blank in the manifest in `onPlacemarkerMouseEnter`.  `this` is not defined.
This PR updates `onPlacemarkerMouseEnter` to use `that` instead of `this`.
(Similar to PR merged for V3: https://github.com/UniversalViewer/universalviewer/pull/792)
> Fix search placemarker hover: use 'that' rather than 'this' when getting defaultLabel

- src/content-handlers/iiif/extensions/uv-aleph-extension/Extension.ts
- src/content-handlers/iiif/extensions/uv-av-extension/Extension.ts
- src/content-handlers/iiif/extensions/uv-default-extension/Extension.ts
- src/content-handlers/iiif/extensions/uv-ebook-extension/Extension.ts
- src/content-handlers/iiif/extensions/uv-mediaelement-extension/Extension.ts
- src/content-handlers/iiif/extensions/uv-model-viewer-extension/Extension.ts
- src/content-handlers/iiif/extensions/uv-openseadragon-extension/Extension.ts
- src/content-handlers/iiif/extensions/uv-pdf-extension/Extension.ts
- src/content-handlers/iiif/modules/uv-shared-module/BaseExtension.ts
> Fixed dynamic imports of locale - removed unused properties

- src/content-handlers/iiif/modules/uv-shared-module/css/range.less
Added .uv parent class to remove input range styles from global scope. 
This matches convention to other partials in the uv-shared-module partials list.
> Scoping input[type=range] to .uv

- package-lock.json
- package.json
Upgraded and audited packages to get rid of three critical vulnerabilities. The only one remaining right now is "xmldom", which is used in a subpackage (@universalviewer/epubjs) to @universalviewer/uv-ebook-components.
> Audited and upgraded packages to solve 3 critical vulnerabilities.

- .codesandbox/ci.json
Node v16 is no longer supported; this raises the Node version used by CodeSandbox to 18, which is the lowest version still under active maintenance.
> Bump CodeSandbox Node version to 18.

- README.md
As discussed in the April Community Call, we need to use absolute rather than relative URLs in the README so that links resolve correctly on the documentation site.
> Remove relative links from README.

- .github/workflows/build-test.yml
- .github/workflows/release.yml
Now that UV requires Node 18, we should use appropriate versions in our GitHub actions. This updates them, as per discussion on today's Community Call.
> Use Node 18 in GitHub Actions.

- src/content-handlers/iiif/modules/uv-searchfooterpanel-module/FooterPanel.ts
Fixes a bug identified in Issue 923 that disabled the next/previous search results buttons when the manifest had a single canvas. https://github.com/UniversalViewer/universalviewer/issues/923
> issue 923 allow search results paging on single page

- CONTRIBUTING.md
As discussed on today's Community Call, this PR makes some improvements to CONTRIBUTING.md to make it more helpful. It adjusts heading levels for consistency, adds a note about the destination of the distribution build, explains our Git workflows, removes some old comments, and includes a few other minor adjustments.
Feedback is welcome!
> Improve CONTRIBUTING.md as per April Community Call discussion.

- README.md
I started to address these README issues;
Twitter - change to X, move to after link for slack
Website - should include link to https://universalviewer.io/
> Fix:Addessed issues in README

- src/content-handlers/iiif/modules/uv-mediaelementcenterpanel-module/MediaElementCenterPanel.ts
Caption support was already there, but was only wired up for video. This adds the existing text track support for audio media as well.
Addresses part of #747 
If approved, this is ready to be merged
> Present captions on audio media

- src/content-handlers/iiif/modules/uv-pagingheaderpanel-module/PagingHeaderPanel.ts
Disable previous button from being accessible via keyboard when on first page #888
> Disable previous button (resolves #888)

- src/content-handlers/iiif/modules/uv-contentleftpanel-module/ContentLeftPanel.ts
- src/content-handlers/iiif/modules/uv-contentleftpanel-module/TreeView.ts
Keeps range open when node selected in index view #1041
> Keep ranges open #1041

- package-lock.json
- package.json
Reverts UniversalViewer/universalviewer#1098
> Adjust pdfjs-dist to reflect actual version being used via CDN.

- src/content-handlers/iiif/modules/uv-shared-module/BaseExtension.ts
- src/content-handlers/iiif/modules/uv-shared-module/css/styles.less
Issue:
The Content Security Policy (CSP) prevents cross-site scripting attacks by blocking inline execution of scripts and style sheets.
To solve this, move all inline scripts (e.g. onclick=[JS code]) and styles into external files.
⚠️ Allowing inline execution comes at the risk of script injection via injection of HTML script elements. If you absolutely must, you can allow inline script and styles by:
adding unsafe-inline as a source to the CSP header
adding the hash or nonce of the inline script to your CSP header.
If possible avoiding the use of unsafe-inline is best.
- Move inline style ```display: none``` to external css class.
> Move inline style to external

- src/content-handlers/iiif/modules/uv-shared-module/FooterPanel.ts
- src/content-handlers/iiif/modules/uv-shared-module/css/footer-panel.less
This PR addresses #952, restoring the functionality of the minimiseButtons configuration option and removing some CSS that is no longer used.
Possibly worth discussing: would it be better to make the minimiseButtons CSS work correctly instead of relying on sr-only here? That would also be a viable solution, it would just require a different set of changes.
> Fix broken minimiseButtons setting.

- src/content-handlers/iiif/modules/uv-pagingheaderpanel-module/css/styles.less
- src/content-handlers/iiif/modules/uv-pdfheaderpanel-module/css/styles.less
- src/content-handlers/iiif/themes/cy-gb/header-panel.less
Fixes #1066 
Removed fixed widths from `.mode label` and `.search` the CY less file.
Changes fixed widths to be auto in the main pdf and paging headerpanel less files.
The auto widths seem fine in all languages at both normal and increased letter spacing, and at all screen widths where the panel appears.
> Remove fixed widths from navigation controls (fixes #1066)

- src/content-handlers/iiif/modules/uv-contentleftpanel-module/ContentLeftPanel.ts
Fixes #955
As noted in the issue, I do not know if this breaks other stuff,
i.e. data that is not shown in openseadragon.
> Address range highlighting bug (Fixes #955)

- src/content-handlers/iiif/modules/uv-searchfooterpanel-module/FooterPanel.ts
Fixes #1100 
Sets aria-label and title on the search button with already-present searchWithin text.
en - Search within this item:
cy - Chwilio tu fewn i:
> Add accessible name to imageButton.searchButton (fixes #1100)

- src/content-handlers/iiif/modules/uv-searchfooterpanel-module/FooterPanel.ts
Fixes #1103 
Only remaining instance was the page position label in the footer:
> Replaced divs with label class with label element (fixes #1103)

- src/content-handlers/iiif/modules/uv-shared-module/BaseExpandPanel.ts
> Keep focus on gallery button when selected

- src/content-handlers/iiif/extensions/uv-openseadragon-extension/DownloadDialogue.tsx
- src/content-handlers/iiif/modules/uv-shared-module/Dialogue.ts
Restrict tab focus to within modal dialogues when open. fix issues #1070 and #1072 
- So the Dialogue.ts which is the Base for the majority of Dialogues now traps the focus when it is opened using a key listener on the TAB and TAB + SHIFT keys
- The Dialogue anomaly is the DownloadDialogue.tsx within the uv-openseadragon extension which is a React component. I have implemented the same here and made some changes following a previous pull request so that we now dynamically get the first focusable element.
> Restrict tab focus to within modal dialogues when open (fixes #1070 and #1072)

- src/content-handlers/iiif/modules/uv-contentleftpanel-module/ContentLeftPanel.ts
- src/content-handlers/iiif/modules/uv-contentleftpanel-module/ThumbsView.tsx
This PR addresses #1068.
Inside the contents left sidebar users can activate images from the thumbnails. They can tab through and then activate the image to make it display in the image viewer.
> Fix keyboard thumbnail activation (fixes #1068)

- src/content-handlers/iiif/modules/uv-contentleftpanel-module/ContentLeftPanel.ts
- src/content-handlers/iiif/modules/uv-contentleftpanel-module/ThumbsView.tsx
- src/content-handlers/iiif/modules/uv-dialogues-module/AdjustImageDialogue.ts
- src/content-handlers/iiif/modules/uv-dialogues-module/ShareDialogue.ts
- src/content-handlers/iiif/modules/uv-openseadragoncenterpanel-module/OpenSeadragonCenterPanel.ts
- src/content-handlers/iiif/modules/uv-pagingheaderpanel-module/PagingHeaderPanel.ts
- src/content-handlers/iiif/modules/uv-pdfcenterpanel-module/PDFCenterPanel.ts
- src/content-handlers/iiif/modules/uv-pdfheaderpanel-module/PDFHeaderPanel.ts
- src/content-handlers/iiif/modules/uv-shared-module/BaseExpandPanel.ts
- src/content-handlers/iiif/modules/uv-shared-module/Panel.ts
Fixes #1084 
Fixes #1157 
All buttons and pseudo-buttons that previously weren't able to be activated via enter/spacebar should now be able to be.
I've modified Panel.ts:onAccessibleClick() to check whether the key is either enter or space and in the case of the latter, prevent the default action (scrolling the page). 
It also now has a fourth arg to specify whether an anchor should be treated as a button i.e. spacebar should activate it. This is for things like tabs where they're an anchor but work like a button.
Some elements that were `<div>` or `<a>` have been changed to `<button>`.
I've also made the thumbnails in the left panel work with space+enter, however the gallery view wasn't possible. For some reason you can't even focus inside it, but as it's the iiif-gallery-component I've …
> Make keyboard activation consistent

- package-lock.json
- package.json
While reviewing #1179, I found that while we include a very old version of chalk in our package.json, we do not appear to use it in any UV-specific code. Several of our command line tools use it as an indirect dependency, but they use newer versions than the one we have pinned. Removing this entirely does not appear to break anything (I can still build, test, lint, etc.).
> Remove obsolete chalk dependency.

- src/content-handlers/iiif/extensions/uv-openseadragon-extension/DownloadDialogue.tsx
When you use a version 3 manifest,
then the format shown next to download option `Whole image w x h (?)` shows a `?`. This is because the code tries to load the image resource the way it is done in version 2.
I added code for version 3 to derive the format
Apparently not a problem for wholeImageLowResLabel
> Fix format in wholeImageHighResLabel when using version 3 manifests

- src/content-handlers/iiif/modules/uv-openseadragoncenterpanel-module/css/styles.less
- src/content-handlers/iiif/modules/uv-shared-module/css/scaffolding.less
1. Buttons after merging [MediaPlayer PR](#1130) were missing normalization. Removed borders and background colors to fix this.
2. Seadragon next page buttons had intended and *bonus backgrounds* from iiif-tree and iiif-gallery. Added LESS to remove the free extras.
> Button normalization

- .github/workflows/update-docs.yml
- package.json
- typedoc.json
This PR fixes a problem that caused the GitHub action for documentation generation to change all of the documentation when documentation was built in a fork of the project. Documentation URLs are now hard-coded in a sourceLinkTemplate instead of inferred from the Git state. Additionally, regeneration of the CNAME document has been moved out of the workflow and into the package.json script, and configuration was moved out of the script and into the config file, all for greater consistency.
> Improve documentation generation workflow.

- package-lock.json
- package.json
The [NPM page for @webpack-cli/serve](https://www.npmjs.com/package/@webpack-cli/serve) says: "This package is used by webpack-cli under-the-hood and is not intended for installation." Since it is included automatically by webpack-cli, we do not need to have a separate explicit dependency on it in package.json; this PR removes it to simplify dependency management. The change has no impact on functionality or which packages get installed.
> Remove unnecessary explicit dependency on @webpack-cli/serve.

- src/uv-iiif-config.json
Displaying the OSD home control is a configurable setting that has historically been off by default. PR #1052 fixed a bug related to the styling of the home button, but it also turned the button on by default, which was probably not desirable, as discussed in #1248.
This PR simply restores the default setting to its previous value, so that release 4.1.0 will behave the same as release 4.0.25.
> Turn off home control by default.

- package-lock.json
- package.json
This PR contains the first release candidate for Universal Viewer 4.1.0. Please test and provide feedback!
Significant changes/new features:
- Image manipulation controls (brightness/contrast/etc.) added to OpenSeadragon component (#1052)
- New defaultToTreeIfCollection config setting (#1107)
- New "extend thumbnail labels" setting (#950)
- Numerous improvements to keyboard navigation, labeling, etc., from the accessibility sprint
- Many dependency updates
- Assorted bug fixes
> Release Candidate: 4.1.0-rc1

- .github/workflows/release.yml
- package-lock.json
- package.json
This is a continuation of #1248. In addition to the changes in the first release candidate, this release also changes the default behavior of the home button (as discussed on the previous PR) and makes an adjustment to the GitHub Actions release workflow to correct a problem that led to an incomplete version of RC1 on NPM.
Normally, these small changes would not justify a second release candidate, but in this instance, the release was necessitated by the NPM publishing glitch.
> Release Candidate: 4.1.0-rc2

- src/content-handlers/iiif/BaseConfig.ts
- src/content-handlers/iiif/IIIFContentHandler.ts
- src/iiif-collection.json
- src/uv-iiif-config.json
It's now possible to use config to override which extensions get loaded depending on your use case. In this case, Exhibit only needs the simple AV experience even when manifests have structure.
> added preferMediaElementExtension config option

- src/index.html
The example form's rotation control was causing strange behavior under some circumstances. Upon investigation, the root cause was the fact that we were passing a string type as if it were a number. Since index.html is not type checked, the compiler didn't catch the problem.
I chose to use `parseInt` on the assumption that we're not interested in fractional rotation values... but I imagine `parseFloat` might be worth considering if we want more granular control for some reason.
> Fix rotation control: ensure rotation value is a number.

- src/UniversalViewer.ts
renamed `_contentType` and `_assignedContentHandler` to remove leading underscore. set them to public.
this is because I use them in Exhibit (they're useful), and have noticed them used elsewhere.
> public internals

- src/content-handlers/iiif/IIIFContentHandler.ts
Due to an order of operations change in #1278, the wrong configuration could be loaded when switching extensions during initialization. This PR is designed to correct the problem.
It is likely there is a more efficient way to do this, and/or that better method names would be preferable. I'm happy to have others modify this!
> Fix an extension configuration bug introduced by #1278.

- src/locales/fr-FR.json
- src/locales/pl-PL.json
- src/locales/sv-SE.json
On our tech call with @crhallberg, @demiankatz and @jamesmisson  we noticed these 3 locale urls had an incorrect _#contributors_ appended. So I created a quick PR to fix that. Fortunately the "more info" link is already configured by locale so we should be able to work on the updated url content independently.
> fixed urls for these locales

- README.md
- docs/index.html
- package-lock.json
- package.json
- src/content-handlers/iiif/extensions/uv-openseadragon-extension/Extension.ts
- src/content-handlers/iiif/modules/uv-shared-module/BaseExpandPanel.ts
- src/content-handlers/iiif/modules/uv-shared-module/LeftPanel.ts
- src/content-handlers/iiif/modules/uv-shared-module/RightPanel.ts
- src/content-handlers/iiif/modules/uv-shared-module/css/catch-all.less
- src/content-handlers/iiif/modules/uv-shared-module/css/sm.less
- src/content-handlers/iiif/modules/uv-shared-module/css/styles.less
Updates CSS and some small JS bits to allow the side panels to appear on mobile.
Currently only tested on OSD extension, but should work the same for all types.
Please excuse the garish colours - they're useful for checking which media queries are running and the stacking of the z-indexes :)
Summary of changes:
- CSS to hide the left and right panels (L & R from now on)  has been removed, building on James' changes. 
- As the panels are now 'visible' all the time, they're pulled off the viewport with a transform property. Aria props set by JS should still apply correctly. 
- The main panel has overflow hidden to allow this method of hiding. For now they still appear on the page just so they're clickable for testing, although in future there'll be header buttons to achieve this.
- At …
> Preliminary sidebar handling css

- src/content-handlers/iiif/extensions/uv-aleph-extension/config/config.json
- src/locales/cy-GB.json
- src/locales/en-GB.json
- src/locales/fr-FR.json
- src/locales/pl-PL.json
- src/locales/sv-SE.json
#1309 
- Updated "More info" links to point to new "About" wiki page
- Fixed small config url bug
> Updated about links

- src/content-handlers/iiif/modules/uv-dialogues-module/ShareDialogue.ts
On [any platform that the UV considers to be mobile](https://github.com/UniversalViewer/universalviewer/blob/dev/src/content-handlers/iiif/modules/uv-shared-module/BaseExtension.ts#L1120-L1132), the UV will hide just the input box for the share menu. 
This fixes that!
> Share Menu: show URL input on mobile.

- package-lock.json
- package.json
- src/content-handlers/iiif/modules/uv-mediaelementcenterpanel-module/MediaElementCenterPanel.ts
Fixes #1364 - adds config so volume controls are still visible  for audio files on mobile devices. 
Works on iPhone with Safari, needs to be tested with other devices/browsers
> Add volume control to audio files on mobile devices

- src/content-handlers/iiif/modules/uv-contentleftpanel-module/css/styles.less
- src/content-handlers/iiif/modules/uv-ebookleftpanel-module/css/styles.less
- src/content-handlers/iiif/modules/uv-shared-module/css/overlays.less
This fixes the contrast issue by bringing tags to AA contrast like the links. If we want AAA contrast, here are some options:
- [Tailwind CSS](https://tailwindcss.com/docs/colors) - cyan 500 is the closest color in this palette. We can move to cyan-300 for text and cyan-700 for buttons.
- [Harmony](https://www.figma.com/community/file/1287828769207775946/harmony-accessible-ui-color-palette) - cyan-300 and cyan-700 for something less vibrant.
- We can switch hues to the purple or fuchsia that we see on the UV website.
> Change active tab to @link-color for contrast.

- src/content-handlers/iiif/modules/uv-shared-module/Dialogue.ts
Fix share and terms conflict by only opening one dialogue at a time.
TODO
> Only One Dialogue Overlay at a Time

- CONTRIBUTING.md
Also splits up the release documentation into more sub-sections, to make the overall flow and numbering more easily digestible.
> Clarify the release candidate process with command examples.

- src/content-handlers/iiif/modules/uv-openseadragoncenterpanel-module/css/styles.less
Closes #1369 
Adjusts the media queries for the OSD controls so they appear on mid-sized devices (tablets and small laptops).
Oddly the fading behaviour in OSD doesn't seem to work when below 1024px, but I don't see that as a problem because at that size it's likely a touch device, so mouse events wouldn't work anyway.
> Make osd controls visible from md+

- package-lock.json
- package.json
This update should eliminate content security policy warnings related to the gallery component, thanks to @anthonyhashemi's work on https://github.com/IIIF-Commons/iiif-gallery-component/pull/31.
> Update to iiif-gallery-component v1.1.23.

- src/content-handlers/iiif/modules/uv-contentleftpanel-module/ThumbsView.tsx
- src/content-handlers/iiif/modules/uv-shared-module/css/thumbs-view.less
Fixes #1409 
Copies colour + image from gallery view component
Removes fixed width from the label which was breaking layout. Selector left commented out in case needed in future (see below)
I would recommend a CSS update of the thumbs view to use grid rather than floats at some point, but I've left it as-is for now.
> Fix thumbnail panel search result display (resolves #1409)

- src/content-handlers/iiif/modules/uv-dialogues-module/AdjustImageDialogue.ts
- src/content-handlers/iiif/modules/uv-dialogues-module/css/styles.less
**Now based on release-4.2.0.**
Having the half-shaded and textured background behind the adjust image overlay makes those adjustments a guessing game. Moving the style adjustment down fixes the proper order of operations to remove the background.
Also:
- add a black border to increase the visual contrast of the overlay.
- move the overlay to the top left to hopefully hide less of the image.
> Fix adjust image dialogue background

- eslint.config.cjs
- src/BaseContentHandler.ts
- src/Init.ts
- src/content-handlers/iiif/IIIFContentHandler.ts
- src/content-handlers/iiif/JQueryPlugins.ts
- src/content-handlers/iiif/URLAdapter.ts
- src/content-handlers/iiif/extensions/uv-av-extension/DownloadDialogue.ts
- src/content-handlers/iiif/extensions/uv-openseadragon-extension/Extension.ts
- src/content-handlers/iiif/modules/uv-alephcenterpanel-module/AlephCenterPanel.ts
- src/content-handlers/iiif/modules/uv-contentleftpanel-module/ContentLeftPanel.ts
- src/content-handlers/iiif/modules/uv-dialogues-module/AdjustImageDialogue.ts
- src/content-handlers/iiif/modules/uv-dialogues-module/AuthDialogue.ts
- src/content-handlers/iiif/modules/uv-dialogues-module/DownloadDialogue.ts
- src/content-handlers/iiif/modules/uv-ebookcenterpanel-module/EbookCenterPanel.ts
- src/content-handlers/iiif/modules/uv-filelinkcenterpanel-module/FileLinkCenterPanel.ts
- src/content-handlers/iiif/modules/uv-mediaelementcenterpanel-module/js/source-chooser-fixed.js
- src/content-handlers/iiif/modules/uv-modelviewercenterpanel-module/ModelViewerCenterPanel.ts
- src/content-handlers/iiif/modules/uv-openseadragoncenterpanel-module/OpenSeadragonCenterPanel.ts
- src/content-handlers/iiif/modules/uv-pagingheaderpanel-module/PagingHeaderPanel.ts
- src/content-handlers/iiif/modules/uv-pdfcenterpanel-module/PDFCenterPanel.ts
- src/content-handlers/iiif/modules/uv-pdfheaderpanel-module/PDFHeaderPanel.ts
- src/content-handlers/iiif/modules/uv-searchfooterpanel-module/FooterPanel.ts
- src/content-handlers/iiif/modules/uv-shared-module/Auth1.ts
- src/content-handlers/iiif/modules/uv-shared-module/BaseExpandPanel.ts
- src/content-handlers/iiif/modules/uv-shared-module/BaseExtension.ts
- src/content-handlers/iiif/modules/uv-shared-module/Panel.ts
- src/content-handlers/iiif/modules/uv-shared-module/TestExternalResource.ts
- src/content-handlers/iiif/modules/uv-shared-module/ThumbsView.ts
Resolves #1429.
Updates the eslint config to error when `let` could/should be `const`
Runs that config over the src directory
Manually changes `canvas` and `uv` vars to be const because ESLint was unable to do it automatically.
> Eslint let const

- .github/workflows/build-test.yml
- .github/workflows/lint-and-prettify.yml
- .github/workflows/release.yml
- package.json
- src/netlify.toml
Node 18 has reached end of life, so it's time to move on to Node 20.
Resolves #1433.
> Raise Node version to 20 in package.json and GitHub Actions.

- src/content-handlers/iiif/BaseConfig.ts
- src/content-handlers/iiif/extensions/uv-aleph-extension/config/config.json
- src/content-handlers/iiif/extensions/uv-av-extension/config/config.json
- src/content-handlers/iiif/extensions/uv-default-extension/config/config.json
- src/content-handlers/iiif/extensions/uv-ebook-extension/config/config.json
- src/content-handlers/iiif/extensions/uv-mediaelement-extension/config/config.json
- src/content-handlers/iiif/extensions/uv-model-viewer-extension/config/config.json
- src/content-handlers/iiif/extensions/uv-openseadragon-extension/config/config.json
- src/content-handlers/iiif/extensions/uv-pdf-extension/config/config.json
Remove the `shareFrameEnabled` config option as per discussion in [1449](https://github.com/UniversalViewer/universalviewer/issues/1449#issuecomment-2991239041)
> removing shareFrameEnabled config option

- package-lock.json
- package.json
This backports the fix from #1467 so that we can release a fixed UV v4.2.1.
Resolves #1464.
> Upgrade iiif-metadata-component to v1.2.2.
