src/modules/uv-shared-module/baseExtension.ts

As per https://groups.google.com/forum/#!topic/universalviewer/fLbye4M974M

Prevent fatal error when running outside of an iframe.

---

src/modules/uv-pagingheaderpanel-module/pagingHeaderPanel.ts
src/modules/uv-searchfooterpanel-module/footerPanel.ts
src/modules/uv-treeviewleftpanel-module/galleryView.ts
src/modules/uv-treeviewleftpanel-module/thumbsView.ts

See also https://github.com/UniversalViewer/examples/pull/1

Made page mode (use of labels instead of image numbers) configurable.

---

src/extensions/uv-seadragon-extension/DownloadOption.ts
src/extensions/uv-seadragon-extension/downloadDialogue.ts
src/extensions/uv-seadragon-extension/l10n/cy-GB.json
src/extensions/uv-seadragon-extension/l10n/en-GB.json
src/extensions/uv-seadragon-extension/l10n/xx-XX.json
src/modules/uv-shared-module/RenderingFormat.ts

This PR adds MS Word support very similar to the existing PDF support. A lot of this feels rather brute-force, and I wonder if there are opportunities to introduce loops in some places to make the creation/showing/hiding of buttons a bit less redundant. However, for the first pass, I opted to simply add the functionality without refactoring very much.

Added support for MS Word downloads.

---

src/bootstrapper.ts

- This should have been part of #62; not sure how I left it out.

Fixed inconsistent implementation of corsEnabled().

---

src/lib/jquery-plugins.js

Revamp toggleExpandTextByLines to a new method tracing element height differences instead of relying on CSS math.
Also prevents elements being shortened with removeLastWord from being deleted outright. Oops.
Restores IE8 compatibility.
Fixes #86

Fix for Issue #86

---

src/modules/uv-shared-module/BaseProvider.ts
src/modules/uv-treeviewleftpanel-module/GalleryView.ts
src/modules/uv-treeviewleftpanel-module/css/styles.less

This PR contains some improvements to make thumbnails work better in the treeViewLeftPanel for audio/video/PDF objects containing multiple elements.

Better thumbnails for audio/video/PDF objects

---

.gitmodules

- Helps with Travis CI
- Simplifies setup for new users

Switched .gitmodules from SSH to HTTPS.

---

.travis.yml

This is a working baseline Travis configuration for the UV. It doesn't run tests yet, but it does perform a build. This alone will be useful for catching problems where Windows-specific quirks cause breaks under Linux.
As time permits, I'll continue to experiment with getting the full test suite running under Travis, but I thought this was a useful starting point for getting the UV under Travis monitoring in some form.
I'm hardly a Travis expert, but I do have a little experience with getting projects set up. Please let me know if I can be of any assistance with any of those details!

Added Travis configuration.

---

src/modules/uv-treeviewleftpanel-module/css/styles.less

This should take care of #133. Thanks, @crhallberg!

Label wrap

---

src/extensions/uv-seadragon-extension/config/en-GB.json

Hi again!
Here are the same configuration options added to the default config file too, hopefully they'll work with the config editor out of the box.

Added the new OSD options to the default config file.

---

src/extensions/uv-seadragon-extension/Extension.ts
src/extensions/uv-seadragon-extension/lib/openseadragon.js
src/modules/uv-shared-module/BaseCommands.ts
src/modules/uv-shared-module/BaseExtension.ts

Hi!
Now that OSD have released version 2.1 containing my patch for zooming with the plus key, here is the complete pull request including OSD 2.1. We have been running OSD from a recent master for two weeks and it's been working fine for us so far.
This patch also makes UV set the focus to OSD when the plus or minus keys is pressed, which then makes OSD zoom. I've tested it in Chrome, FF and IE 11.

OSD 2.1 with patch for zooming.

---

src/extensions/uv-seadragon-extension/config/en-GB.json
src/modules/uv-pagingheaderpanel-module/PagingHeaderPanel.ts
src/modules/uv-pagingheaderpanel-module/css/styles.less

I'm not sure you were interested in this feature or we were suppossed to wait with all these kind of changes. Anyway here it is and it's disabled by default.

Adding image dropdown to header panel

---

package.json
src/extensions/uv-virtex-extension/lib/virtex.js
src/lib/manifesto.js
src/modules/uv-dialogues-module/ClickThroughDialogue.ts
src/modules/uv-dialogues-module/RestrictedDialogue.ts
src/modules/uv-shared-module/BaseCommands.ts
src/modules/uv-shared-module/BaseExtension.ts
src/modules/uv-shared-module/ExternalResource.ts
src/typings/manifesto.d.ts

Add restricted auth dialogue and flow; allow getAuthToken to fail without rejecting

Standardise auth

---

README.md

Not really worth a PR but should go by the book.

Update README.md to link to About page

---

src/modules/uv-shared-module/BaseExtension.ts

Currently you can't use the keyboard minus and plus keys to zoom.

Fix for zooming with minus and plus keys

---

src/modules/uv-pagingheaderpanel-module/PagingHeaderPanel.ts

Found XSS vulnerability in image selection box. Fixed it using the sanitize method like in MoreInfoRightPanel and SeadragonCenterPanel..

XSS vulnerability in image selection box

---

src/modules/uv-seadragoncenterpanel-module/SeadragonCenterPanel.ts

see issue https://github.com/UniversalViewer/universalviewer/issues/403

change maxZoomLevel to maxZoomPixelRatio

---

src/extensions/uv-seadragon-extension/DownloadDialogue.ts
src/extensions/uv-seadragon-extension/Extension.ts

- There are still download options that are hidden in two-up mode. So we still need this note.

Restore paging note

---

src/lib/embed.js

Added EmbedJS back and updated to preserve backward compatibility for old URLs

Added EmbedJS back and updated

---

src/modules/uv-shared-module/ThumbsView.ts

For accessibility, see https://www.w3.org/WAI/tutorials/images/functional/#logo-image-within-link-text as a similar example
Partially addresses https://github.com/sul-dlss/universalviewer/issues/25

Adds alt attribute for image thumbs

---

src/uv.html

Fix for https://github.com/UniversalViewer/universalviewer/issues/449

Read locales parameter from url

---

src/modules/uv-shared-module/BaseExtension.ts

Fix for https://github.com/UniversalViewer/universalviewer/issues/476

Fix for Issue 476: exiting full screen didn't resize screen

---

src/modules/uv-virtexcenterpanel-module/VirtexCenterPanel.ts
src/modules/uv-virtexcenterpanel-module/css/icons.less
src/modules/uv-virtexcenterpanel-module/css/styles.less

convert virtex icons to consolidated approach

---

src/extensions/uv-av-extension/config/en-GB.json
src/extensions/uv-seadragon-extension/config/en-GB.json
src/modules/uv-shared-module/css/variables.less

desktop height fix

---

src/extensions/uv-mediaelement-extension/l10n/en-GB.json

Added share config to mediaelement footer so it displays "Share" instead of "undefined"

Mediaelement share

---

Gruntfile.js
tsconfig.json

Fixes #566 ... needed to start to address #567

move Grunt typescript config to a standardized tsconfig.json

---

src/uv.html

Fix for the issue in Firefox where the event listener wasn't picking up the uvLoaded event

Firefox refresh fix

---

package-lock.json

This fixes the broken build in master.

Fix problem in package lock.

---

src/extensions/uv-av-extension/DownloadDialogue.ts
src/modules/uv-dialogues-module/DownloadDialogue.ts

Enabling downloads for Manifest, Canvas, and Image renderings within the DownloadDialogue for A/V resources

---

src/extensions/uv-pdf-extension/Extension.ts
src/extensions/uv-pdf-extension/config/en-GB.json
src/modules/uv-pdfcenterpanel-module/PDFCenterPanel.ts

usePdfJs config - hide header panel for pdfobject

usePdfJs config - hide header panel for pdfobject

---

src/modules/uv-pdfcenterpanel-module/PDFCenterPanel.ts

This code displays the attribution box for PDFs when using PDFObject.

Display attribution box for PDFObject

---

src/modules/uv-shared-module/BaseExtension.ts

Adds missing class when reloading the UV configuration in fullscreen.

Fixed reloading configuration in full-screen

---

src/extensions/uv-av-extension/l10n/pl-PL.json
src/extensions/uv-default-extension/l10n/pl-PL.json
src/extensions/uv-ebook-extension/l10n/pl-PL.json
src/extensions/uv-mediaelement-extension/l10n/pl-PL.json
src/extensions/uv-pdf-extension/l10n/pl-PL.json
src/extensions/uv-seadragon-extension/l10n/pl-PL.json
src/extensions/uv-virtex-extension/l10n/pl-PL.json

Added polish translations

---

src/modules/uv-shared-module/CenterPanel.ts

By this commit the dom element id "content" is being renamed  to "uv-content". This fixes #713
The change does not add failures to the result of `npm test`.

removing dom element id "content", fixes #713

---

src/URLAdaptor.ts

Adds optional extra helper to URL adapter.
```javascript
const urlAdaptor = new UV.UrlAdapter();
const data = urlAdaptor.getInitialData({
embedded: true,
})
const uv = UV.init("uv", data);
urlAdapter.bindTo(uv);
```

Extra URL adapter helper

---

package-lock.json
package.json

Fixes #836 contains https://github.com/IIIF-Commons/iiif-av-component/pull/53

Update AV component version (1.1.8)

---

package-lock.json
package.json
src/content-handlers/iiif/extensions/uv-av-extension/theme/theme.less
src/content-handlers/iiif/modules/uv-avcenterpanel-module/AVCenterPanel.ts

Range change bug 

---

package-lock.json
package.json
src/UniversalViewer.ts

Added WAV mediatype to the extension registry as a type which should load the AVComponent

Load AV component for MediaType WAV #828

---

src/content-handlers/iiif/modules/uv-avcenterpanel-module/css/styles.less
src/content-handlers/iiif/modules/uv-moreinforightpanel-module/MoreInfoRightPanel.ts
src/content-handlers/iiif/modules/uv-shared-module/BaseExtension.ts
src/content-handlers/iiif/modules/uv-shared-module/css/center-panel.less
src/content-handlers/iiif/modules/uv-shared-module/css/xl.less
src/index.html
tsconfig.json

_Few fixes to the AV component covering configuration and styling._

AV Component fixes

---

package-lock.json
package.json

Updated to preview of av component

---

src/content-handlers/iiif/modules/uv-searchfooterpanel-module/css/styles.less

Changed width of container to make "Next result" button more visible on the Welsh translation. Relating to issue #903

Fixing width of search results container (.controls) for issue #903

---

src/uv.html

This PR fixes two small issues with the current `uv.html` file. Our team ran into these issues when upgrading from UV3 to UV4, using the default `uv.html` as a starting point. 
- Fixes bug where `configUrl` code doesn't successfully load config from URL parameter. This PR borrows the code from the previously created sandbox example for loading UV config settings (https://codesandbox.io/s/uv-config-example-7kh4s?file=/index.html). This restores config loading functionality.
- Fixes bug where resize event listener was not firing when browser window is resized. Resize now fires when it's supposed to.

Fix minor uv.html issues with config loading and resize handling

---

src/content-handlers/iiif/modules/uv-pdfcenterpanel-module/PDFCenterPanel.ts

Updated the CDN links for pdf.js per discussion in https://github.com/UniversalViewer/universalviewer/issues/939

CDN fix for PDF.js

---

src/content-handlers/iiif/modules/uv-mediaelementcenterpanel-module/MediaElementCenterPanel.ts

The previous logic was putting some non-media elements into sources (xml, txt) and wasn't adding captions when renderings were used. This should fix both those problems.
Example manifest: https://digital.library.villanova.edu/Item/vudl:829943/Manifest

Video: sort video and caption elements

---

src/content-handlers/iiif/extensions/uv-openseadragon-extension/config/config.json
src/content-handlers/iiif/extensions/uv-pdf-extension/config/config.json

The "Two page view" option in the settings dialogue was incorrectly renamed "Go Home" between v4.0.0 and 4.0.25 so I changed it back.

Rename "Go Home" in settings dialogue

---

src/content-handlers/iiif/BaseConfig.ts
src/content-handlers/iiif/extensions/uv-aleph-extension/config/config.json
src/content-handlers/iiif/extensions/uv-av-extension/config/config.json
src/content-handlers/iiif/extensions/uv-default-extension/config/config.json
src/content-handlers/iiif/extensions/uv-ebook-extension/config/config.json
src/content-handlers/iiif/extensions/uv-mediaelement-extension/config/config.json
src/content-handlers/iiif/extensions/uv-model-viewer-extension/config/config.json
src/content-handlers/iiif/extensions/uv-openseadragon-extension/config/config.json
src/content-handlers/iiif/extensions/uv-pdf-extension/config/config.json
src/content-handlers/iiif/modules/uv-shared-module/CenterPanel.ts

Properly translate attribution close label (fixes #1083)

---

src/content-handlers/iiif/extensions/uv-pdf-extension/config/Config.ts
src/content-handlers/iiif/extensions/uv-pdf-extension/config/config.json
src/content-handlers/iiif/modules/uv-openseadragoncenterpanel-module/OpenSeadragonCenterPanel.ts
src/content-handlers/iiif/modules/uv-pdfcenterpanel-module/PDFCenterPanel.ts

Add focus highlight to previous/next buttons in center panel 

---

src/content-handlers/iiif/modules/uv-pdfheaderpanel-module/PDFHeaderPanel.ts

Disallow tabbing to buttons when they're disabled

---

src/content-handlers/iiif/modules/uv-shared-module/css/styles.less

Add focus highlight to gallery control buttons

---

package-lock.json
package.json

This PR upgrades to the latest release of https://github.com/IIIF-Commons/iiif-gallery-component/ which includes a fix to #1067.

Update @iiif/iiif-gallery-component to v1.1.22.

---

src/content-handlers/iiif/modules/uv-openseadragoncenterpanel-module/OpenSeadragonCenterPanel.ts

Correct minor regression from #1158; add tabindex for consistency.

---

src/content-handlers/iiif/BaseConfig.ts
src/content-handlers/iiif/extensions/uv-aleph-extension/config/config.json
src/content-handlers/iiif/extensions/uv-av-extension/config/config.json
src/content-handlers/iiif/extensions/uv-default-extension/config/config.json
src/content-handlers/iiif/extensions/uv-ebook-extension/config/config.json
src/content-handlers/iiif/extensions/uv-mediaelement-extension/config/config.json
src/content-handlers/iiif/extensions/uv-model-viewer-extension/config/config.json
src/content-handlers/iiif/extensions/uv-openseadragon-extension/config/config.json
src/content-handlers/iiif/extensions/uv-pdf-extension/config/config.json
src/content-handlers/iiif/modules/uv-shared-module/CenterPanel.ts
src/locales/cy-GB.json
src/locales/en-GB.json
src/locales/fr-FR.json
src/locales/pl-PL.json
src/locales/sv-SE.json

Fixes #1075 
Supersedes #1160 
Applies option 1 from https://github.com/UniversalViewer/universalviewer/pull/1160#pullrequestreview-2388177647
@demiankatz I think this is what you described in option 1 but this is my first typescript project so please excuse any misunderstandings!

Changes attribution close button label. Fixes #1075

---

GOVERNANCE.md

Add governance document.

---

CONTRIBUTING.md

This PR corrects inaccurate documentation to reflect the realities discussed in #950.

Correct inaccurate note about test suite.

---

package-lock.json
package.json

This PR upgrades the iiif-metadata-component to the latest release. This should address several issues: #973, #1081, #1085

Update iiif-metadata-component to v1.2.0.

---

esbuild.mjs
package-lock.json
package.json

This continues #1260, correcting some more NPM deployment issues.

Release Candidate: 4.1.0-rc3

---

package-lock.json
package.json

Hopefully final release candidate, following on from #1266 and incorporating fixes from #1267.

Release candidate: 4.1.0-rc5

---

src/content-handlers/iiif/modules/uv-mediaelementcenterpanel-module/MediaElementCenterPanel.ts

removed the autoplay of 1 second as it was unneeded

remove autoplay 1s

---

src/BaseContentHandler.ts
src/content-handlers/iiif/IIIFContentHandler.ts
src/content-handlers/iiif/IIIFData.ts
src/content-handlers/iiif/IIIFEvents.ts
src/content-handlers/iiif/extensions/uv-mediaelement-extension/Events.ts
src/content-handlers/iiif/extensions/uv-mediaelement-extension/Extension.ts
src/content-handlers/iiif/modules/uv-mediaelementcenterpanel-module/MediaElementCenterPanel.ts
src/index.html

Added a new mute checkbox to index.html that calls `uv.set({ mute: true/false })`
Clicking on the mute button in mediaelement or reducing volume to 0 also triggers corresponding `mediaelementExtension.mediaMuted` and `mediaelementExtension.mediaUnmuted` events that can be listened for on the uv.

Added mute/unmute feature

---

package-lock.json
package.json

Another RC, building on #1268 and incorporating a bug fix, dependency updates, and adjustments to the test suite runner (which broke due to external forces).

Release candidate: 4.1.0-rc6

---

package-lock.json
package.json

The next release candidate, building on #1276 by adding a couple of minor AV features and fixing a bug with the rotation control on the example page.

Release candidate: 4.1.0-rc7

---

src/content-handlers/iiif/extensions/uv-mediaelement-extension/Extension.ts
src/content-handlers/iiif/extensions/uv-mediaelement-extension/IMediaElementExtension.ts
src/content-handlers/iiif/modules/uv-mediaelementcenterpanel-module/MediaElementCenterPanel.ts
src/iiif-collection.json

mediaelementextension now also looks for an accompanying canvas for the poster image

use accompanying canvas for poster image

---

package-lock.json
package.json

This PR builds upon #1284, fixing a couple more last-minute bugs.

Release candidate: 4.1.0-rc9

---

package-lock.json
package.json

This should resolve #1344, if I built the new release correctly!

Upgrade iiif-tree-component to v2.0.7.

---

src/index.ts

Restores the UK spelling, IIIFURLAdaptor, in case anyone's using it with v4

Restore UK spelling alias IIIFURLAdapter/IIIFURLAdaptor

---

src/index.html

Added a checkbox in custom configuration to clear browser storage and session. Fixes #1407

Add clear browser storage/session checkbox in custom configuration control (Fixes #1407)

---

README.md

Add link to Mastodon account to the social media links on README.md

add Mastodon link to README.md

---

ARCHITECTURE.md

Here are some brief descriptions of the dialogues. Some of these aren't functional, or partially functional, but I've stuck to explaining what they should do here.

Architecture
